"""add deleted_at to workspaces

Revision ID: a10ae1555f75
Revises: a8c4d3e9f021
Create Date: 2026-05-06 23:24:36.087951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'a10ae1555f75'
down_revision: Union[str, Sequence[str], None] = 'a8c4d3e9f021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间，NULL 表示未删除'))
    op.create_index(op.f('ix_workspaces_deleted_at'), 'workspaces', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_deleted_at'), table_name='workspaces')
    op.drop_column('workspaces', 'deleted_at')
    # ### end Alembic commands ###
