apiVersion: apps/v1
kind: Deployment
metadata:
  name: dewflow-worker
  namespace: dewflow
spec:
  template:
    spec:
      containers:
        - name: worker
          imagePullPolicy: Never
          command:
            - python
            - -c
            - "import time; time.sleep(3600)"
          livenessProbe: null
          readinessProbe: null
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
