import { test, expect } from '@playwright/test';

test.skip(() => !process.env.E2E_SMOKE, 'Requires running backend (set E2E_SMOKE=1)');

test.describe('Real backend: login + profile', () => {
  test('login with real credentials and fetch /users/me', async ({ page }) => {
    await page.goto('/');

    await page.getByTestId('user-menu-btn').click();
    // Guest user-menu-btn directly opens the AuthModal (no intermediate menu)

    const randomPhone = `138${Math.floor(10000000 + Math.random() * 90000000)}`;
    await page.locator('.auth-modal').locator('input#phone-login_phone').fill(randomPhone);
    await page.locator('.auth-modal').getByRole('button', { name: '发送验证码' }).click();

    // Read the mock demo code generated by the backend and displayed on the UI
    const demoCode = await page.locator('.auth-modal').locator('strong').textContent();
    await expect(demoCode).not.toBeNull();

    await page.locator('.auth-modal').locator('input[maxlength="6"]').fill(demoCode!);
    await page.locator('.auth-modal').locator('button[type="submit"]').click();

    await expect(page.locator('.avatar-badge:not(.guest)')).toBeVisible();

    await expect(page.locator('.sidebar-hint, [data-testid="session-item"]').first()).toBeVisible({
      timeout: 15000,
    });
  });
});
